# Generated by Django 2.0.7 on 2021-11-24 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20211123_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 24, 5, 24, 27, 544985, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
